// Public entry point for occupational standards.
//
// Standards are compiled from standards/*.yaml into ./generated by
// `npm run standards:build`. Import from here, never from ./generated directly.

import { STANDARDS, STANDARD_IDS, type StandardId } from "./generated";
import type { AssessmentMethod, Ksb, MethodKey, Standard } from "./types";

export type {
  AssessmentMethod,
  Category,
  Colour,
  Ksb,
  MethodKey,
  Standard,
  SubPoint,
} from "./types";
export { STANDARDS, STANDARD_IDS, type StandardId };

/**
 * Used for portfolios whose repo has no `datafolio.yml`. Every repo created
 * before standards were configurable is an ST0585 portfolio, so this keeps them
 * working untouched.
 */
export const DEFAULT_STANDARD_ID = "st0585";

export function isStandardId(id: string): id is StandardId {
  return id in STANDARDS;
}

/** Resolve a standard by id, falling back to the default for unknown ids. */
export function getStandard(id: string | null | undefined): Standard {
  if (id && isStandardId(id)) return STANDARDS[id];
  return STANDARDS[DEFAULT_STANDARD_ID];
}

/** KSBs and sub-points indexed by code, e.g. "K3" and "K3.1". */
export function ksbIndex(standard: Standard): Record<string, Ksb> {
  return Object.fromEntries(standard.ksbs.map((k) => [k.id, k]));
}

/** Every valid evidence target in a standard — KSB codes plus sub-point codes. */
export function validKsbIds(standard: Standard): Set<string> {
  return new Set(
    standard.ksbs.flatMap((k) => [
      k.id,
      ...(k.points ?? []).map((p) => p.id),
    ]),
  );
}

export function methodsOf(
  standard: Standard,
  keys: MethodKey[],
): AssessmentMethod[] {
  return keys.map((k) => standard.methods[k]).filter(Boolean);
}

/** Methods learners actively gather portfolio evidence against. */
export function collectingMethods(standard: Standard): AssessmentMethod[] {
  return Object.values(standard.methods).filter((m) => m.collectsEvidence);
}

/**
 * Whether a KSB expects portfolio evidence at all. False for KSBs assessed only
 * by methods that do not collect evidence (currently the knowledge test), which
 * are shown for completeness but never prompt the learner for artefacts.
 */
export function collectsEvidence(standard: Standard, ksb: Ksb): boolean {
  return ksb.methods.some((m) => standard.methods[m]?.collectsEvidence);
}
